<?php

namespace ContainerGcls2ds;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getGiteService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.errored..service_locator.a4.yDU4.App\Entity\Gite' shared service.
     *
     * @return \App\Entity\Gite
     */
    public static function do($container, $lazyLoad = true)
    {
        $container->throw('Cannot autowire service ".service_locator.a4.yDU4": it references class "App\\Entity\\Gite" but no such service exists.');
    }
}
