<?php

namespace ContainerRBxVtHW;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_XheqsZuService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.XheqsZu' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.XheqsZu'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'notification' => ['privates', 'App\\Notification\\ContactNotification', 'getContactNotificationService', true],
        ], [
            'notification' => 'App\\Notification\\ContactNotification',
        ]);
    }
}
