<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerU3jxvAl\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerU3jxvAl/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerU3jxvAl.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerU3jxvAl\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerU3jxvAl\App_KernelDevDebugContainer([
    'container.build_hash' => 'U3jxvAl',
    'container.build_id' => 'c739ff75',
    'container.build_time' => 1654807493,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerU3jxvAl');
