<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerJy0wSRn\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerJy0wSRn/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerJy0wSRn.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerJy0wSRn\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerJy0wSRn\App_KernelDevDebugContainer([
    'container.build_hash' => 'Jy0wSRn',
    'container.build_id' => '8434d089',
    'container.build_time' => 1655065206,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerJy0wSRn');
