<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerGcls2ds\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerGcls2ds/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerGcls2ds.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerGcls2ds\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerGcls2ds\App_KernelDevDebugContainer([
    'container.build_hash' => 'Gcls2ds',
    'container.build_id' => '3880dc02',
    'container.build_time' => 1655326655,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerGcls2ds');
