<?php

// This file has been auto-generated by the Symfony Routing Component.

return [
    'admin_index' => [[], ['_controller' => 'App\\Controller\\Admin\\adminController::index'], [], [['text', '/admin']], [], [], []],
    'admin_gite_create' => [[], ['_controller' => 'App\\Controller\\Admin\\adminController::create'], [], [['text', '/admin/gite/create']], [], [], []],
    'admin_gite_edit' => [['id'], ['_controller' => 'App\\Controller\\Admin\\adminController::edit'], [], [['variable', '/', '[^/]++', 'id', true], ['text', '/admin/gite/create/edit']], [], [], []],
    'admin_gite_delete' => [['id'], ['_controller' => 'App\\Controller\\Admin\\adminController::delete'], [], [['variable', '/', '[^/]++', 'id', true], ['text', '/admin/gite/delete']], [], [], []],
    'gite_show' => [['id'], ['_controller' => 'App\\Controller\\GiteController::show'], [], [['variable', '/', '[^/]++', 'id', true], ['text', '/gite']], [], [], []],
    'app_login' => [[], ['_controller' => 'App\\Controller\\SecurityController::login'], [], [['text', '/login']], [], [], []],
    'app_logout' => [[], ['_controller' => 'App\\Controller\\SecurityController::logout'], [], [['text', '/logout']], [], [], []],
    'home' => [[], ['_controller' => 'App\\Controller\\homeController::index'], [], [['text', '/']], [], [], []],
    'contact' => [[], ['_controller' => 'App\\Controller\\homeController::contact'], [], [['text', '/contact']], [], [], []],
    'recherche-gite' => [[], ['_controller' => 'App\\Controller\\homeController::rechercheGite'], [], [['text', '/recherche-gite']], [], [], []],
    'detailGite' => [[], ['_controller' => 'App\\Controller\\homeController::detailGite'], [], [['text', '/detail-gite']], [], [], []],
    '_preview_error' => [['code', '_format'], ['_controller' => 'error_controller::preview', '_format' => 'html'], ['code' => '\\d+'], [['variable', '.', '[^/]++', '_format', true], ['variable', '/', '\\d+', 'code', true], ['text', '/_error']], [], [], []],
    '_wdt' => [['token'], ['_controller' => 'web_profiler.controller.profiler::toolbarAction'], [], [['variable', '/', '[^/]++', 'token', true], ['text', '/_wdt']], [], [], []],
    '_profiler_home' => [[], ['_controller' => 'web_profiler.controller.profiler::homeAction'], [], [['text', '/_profiler/']], [], [], []],
    '_profiler_search' => [[], ['_controller' => 'web_profiler.controller.profiler::searchAction'], [], [['text', '/_profiler/search']], [], [], []],
    '_profiler_search_bar' => [[], ['_controller' => 'web_profiler.controller.profiler::searchBarAction'], [], [['text', '/_profiler/search_bar']], [], [], []],
    '_profiler_phpinfo' => [[], ['_controller' => 'web_profiler.controller.profiler::phpinfoAction'], [], [['text', '/_profiler/phpinfo']], [], [], []],
    '_profiler_search_results' => [['token'], ['_controller' => 'web_profiler.controller.profiler::searchResultsAction'], [], [['text', '/search/results'], ['variable', '/', '[^/]++', 'token', true], ['text', '/_profiler']], [], [], []],
    '_profiler_open_file' => [[], ['_controller' => 'web_profiler.controller.profiler::openAction'], [], [['text', '/_profiler/open']], [], [], []],
    '_profiler' => [['token'], ['_controller' => 'web_profiler.controller.profiler::panelAction'], [], [['variable', '/', '[^/]++', 'token', true], ['text', '/_profiler']], [], [], []],
    '_profiler_router' => [['token'], ['_controller' => 'web_profiler.controller.router::panelAction'], [], [['text', '/router'], ['variable', '/', '[^/]++', 'token', true], ['text', '/_profiler']], [], [], []],
    '_profiler_exception' => [['token'], ['_controller' => 'web_profiler.controller.exception_panel::body'], [], [['text', '/exception'], ['variable', '/', '[^/]++', 'token', true], ['text', '/_profiler']], [], [], []],
    '_profiler_exception_css' => [['token'], ['_controller' => 'web_profiler.controller.exception_panel::stylesheet'], [], [['text', '/exception.css'], ['variable', '/', '[^/]++', 'token', true], ['text', '/_profiler']], [], [], []],
];
